### ISSUE TITLE
incompatible with pandas 1.0.3

### ISSUE THREAD

**Issue by Djoels** [ML-KULeuven/cobras#2]
When installing through pypi I could only get the gui demo working if I downgraded to pandas 0.23.1.
Error message was that dataframe does not have attribute "ix".

**Comment by jonassoenen** [comment]
Hi Djoels, 

This issue is solved now COBRAS is updated to work with the newest version of pandas. 
Installing the newest version from PyPi should work now with pandas 1.0.3.

Jonas
